<?php

namespace Nurun\Bundle\RhBundle\Entity;

/**
 * AdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByCodeAndNumber($code,$number)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.codePostal = :cp')
            ->setParameter('cp', $code)
            ->andWhere('a.numeroAdresse = :num')
            ->setParameter('num', $number);

        return $adresse = $qb
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findByMandat($mandat)
    {
//        $qb = $this->createQueryBuilder('a');
        $em = $this->getEntityManager();
        $query=$em->createQuery("select a from NurunRhBundle:Adresse a where :mandatId MEMBER OF a.mandats")
            ->setParameter("mandatId", $mandat);
        $results=$query->getResult();
        return $results;
    }

}
