<?php

namespace Nurun\Bundle\RhBundle\Entity;

/**
 * CertificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificationRepository extends \Doctrine\ORM\EntityRepository
{
}
