<?php

namespace Nurun\Bundle\RhBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConseillerRdpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConseillerRdpRepository extends EntityRepository
{
    public function findActifRdp($conseiller)
    {
        $qb = $this->createQueryBuilder('c');
     
        $qb->where('c.conseiller = :conseiller')
            ->setParameter('conseiller', $conseiller)
            ->andWhere('c.deletedAt is null')
            ->andWhere('c.dateFin is null')
        ;
         
     $conseillerRdp=$qb
             ->getQuery()
             ->getOneOrNullResult()
             ;
  
     return $conseillerRdp;
    }
    
    public function closeAllRdp($id, $dateDebut)
    {
        $repository = $this
        ->getEntityManager()
        ->getRepository('NurunRhBundle:Conseiller');
        $conseiller = $repository->find($id);
        
        $rdps = $this->findByConseiller($conseiller);

        // $em = $this->getDoctrine()->getManager();
        $em = $this->getEntityManager();
        foreach ($rdps as $rdp)
        {
            if (empty($rdp->getDateFin()))
            {
            $rdp->setDateFin($dateDebut);
            $em->persist($rdp);
            $em->flush();   
            }
        }
  
         return true;
    }

    public function findRessourcesByRdp($conseiller)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.rdp = :rdp')
            ->setParameter('rdp', $conseiller)
            ->andWhere('c.dateFin is null')
            ->andWhere('c.deletedAt is null')
        ;

        $conseillersRdps=$qb
            ->getQuery()
            ->getResult()
        ;
        return $conseillersRdps;
    }
}
