<?php

namespace Nurun\Bundle\RhBundle\Entity;

/**
 * FonctionPermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionPermissionRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByFonctionAndAction($fonction, $action)
	{	
		$qb = $this
			->createQueryBuilder('fp')
			->where('fp.fonction = :fonction')
			->setParameter('fonction', $fonction)
			->andWhere('fp.action = :action')
			->setParameter('action', $action)
		;

		return $qb
			->getQuery()
			->getResult()
		;
	}
}
