<?php

namespace Nurun\Bundle\RhBundle\Entity;

/**
 * PrioriteBesoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrioriteBesoinRepository extends \Doctrine\ORM\EntityRepository
{
}
