<?php

namespace Nurun\Bundle\RhBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatutAffectationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutAffectationRepository extends EntityRepository
{
}
