<?php

namespace Nurun\Bundle\RhBundle\Entity;

/**
 * UserNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNotificationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByUserAndAction($user, $action)
	{	
		$qb = $this
			->createQueryBuilder('un')
			->where('un.user = :user')
			->setParameter('user', $user)
			->andWhere('un.action = :action')
			->setParameter('action', $action)
		;

		return $qb
			->getQuery()
			->getResult()
		;
	}
}
