<?php

namespace Nurun\Bundle\RhBundle\Entity;

/**
 * ConseillerFonctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFonctionRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByUserAndFonction($user, $fonction)
	{	
		$qb = $this
			->createQueryBuilder('uf')
			->where('uf.fonction = :fonction')
			->setParameter('fonction', $fonction)
			->andWhere('uf.user = :user')
			->setParameter('user', $user)
		;

		return $qb
			->getQuery()
			->getOneOrNullResult()
		;
	}
}