<?php

namespace Nurun\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PermissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionsRepository extends EntityRepository
{
}
